import type { AppRecord, AuditLog, AppSetting, RecordMeta } from "@/lib/types";

const now = "2026-06-23T09:00:00.000Z";

function record(input: Omit<AppRecord, "id" | "createdAt" | "updatedAt" | "meta"> & { id: string; meta?: RecordMeta }): AppRecord {
  return {
    meta: {},
    createdAt: now,
    updatedAt: now,
    ...input
  };
}

export const seedRecords: AppRecord[] = [
  record({
    id: "ticket-0001",
    module: "tickets",
    code: "TKT-2569-00001",
    title: "เปิด notebook ไม่ติด",
    description: "เครื่องเปิดไม่ติดหลังจาก Windows Update ขอให้ IT ตรวจสอบ",
    status: "ปิด",
    priority: "ปกติ",
    category: "แจ้งซ่อมอุปกรณ์",
    owner: "System Administrator",
    department: "IT Department",
    dueDate: "2026-06-23",
    meta: { assignee: "IT Support", sla: "สำเร็จ", requester: "System Administrator" }
  }),
  record({
    id: "ticket-0002",
    module: "tickets",
    code: "TKT-2569-00002",
    title: "ทดสอบเครื่องพิมพ์",
    description: "เครื่องพิมพ์ฝ่ายบัญชีพิมพ์ช้า ต้องการตรวจ network",
    status: "เปิด",
    priority: "ปกติ",
    category: "อื่นๆ",
    owner: "System Administrator",
    department: "Finance",
    dueDate: "2026-06-24",
    meta: { assignee: "Unassigned", sla: "เหลือ 12 ชม.", requester: "System Administrator" }
  }),
  record({
    id: "ticket-0003",
    module: "tickets",
    code: "TKT-2569-00003",
    title: "ติดตั้งโปรแกรมประชุมออนไลน์",
    description: "ผู้ใช้ใหม่ต้องการโปรแกรมประชุมและสิทธิ์เข้า meeting room",
    status: "แก้แล้ว",
    priority: "ต่ำ",
    category: "ติดตั้งโปรแกรม",
    owner: "System Administrator",
    department: "HR",
    dueDate: "2026-06-24",
    meta: { assignee: "IT Support", sla: "สำเร็จ", requester: "System Administrator" }
  }),
  record({
    id: "service-0001",
    module: "service-requests",
    code: "SR-2569-00001",
    title: "ขอเปิดใช้งาน Microsoft 365",
    description: "พนักงานใหม่ฝ่าย HR ต้องการ mailbox และ Teams",
    status: "รออนุมัติ",
    priority: "ปกติ",
    category: "Software",
    owner: "HR Officer",
    department: "HR",
    meta: { assignee: "IT Support", requestDate: "2026-06-23" }
  }),
  record({
    id: "service-0002",
    module: "service-requests",
    code: "SR-2569-00002",
    title: "ขอเพิ่มพื้นที่ OneDrive",
    description: "พื้นที่ใกล้เต็มจากไฟล์งานโครงการ",
    status: "กำลังดำเนินการ",
    priority: "ต่ำ",
    category: "Cloud",
    owner: "Project Admin",
    department: "Operations",
    meta: { assignee: "System Administrator", requestDate: "2026-06-22" }
  }),
  record({
    id: "access-0001",
    module: "access-requests",
    code: "AR-2569-00001",
    title: "สิทธิ์เข้าโฟลเดอร์ Finance",
    description: "ขอสิทธิ์ read-only สำหรับตรวจเอกสาร",
    status: "รออนุมัติ",
    priority: "สูง",
    category: "Shared Drive",
    owner: "Finance Manager",
    department: "Finance",
    dueDate: "2026-06-30",
    meta: { permission: "Read only", durationDays: 30 }
  }),
  record({
    id: "access-0002",
    module: "access-requests",
    code: "AR-2569-00002",
    title: "VPN สำหรับทำงานนอกสถานที่",
    description: "ต้องใช้ VPN ระหว่างเยี่ยมสาขา",
    status: "อนุมัติแล้ว",
    priority: "ปกติ",
    category: "VPN",
    owner: "Field Engineer",
    department: "IT Department",
    dueDate: "2026-07-10",
    meta: { permission: "Temporary VPN", durationDays: 14 }
  }),
  record({
    id: "pm-0001",
    module: "pm-calendar",
    code: "PM-2569-00001",
    title: "ตรวจสุขภาพ UPS ห้อง Server",
    description: "ทดสอบ battery, bypass และ alert",
    status: "ครบกำหนด",
    priority: "สูง",
    category: "monthly",
    owner: "IT Support",
    department: "IT Department",
    dueDate: "2026-06-28",
    meta: { asset: "UPS-Server-01", lastDone: "2026-05-28", color: "#0ea5e9" }
  }),
  record({
    id: "pm-0002",
    module: "pm-calendar",
    code: "PM-2569-00002",
    title: "อัปเดต Firmware Access Point",
    description: "ตรวจ firmware และ reboot นอกเวลางาน",
    status: "วางแผน",
    priority: "ปกติ",
    category: "quarterly",
    owner: "Network Admin",
    department: "IT Department",
    dueDate: "2026-07-05",
    meta: { asset: "AP-HQ-02", lastDone: "2026-04-05", color: "#22c55e" }
  }),
  record({
    id: "asset-0001",
    module: "assets",
    code: "IT-2569-00001",
    title: "Notebook Dell Latitude 7440",
    description: "Core i7 / 16GB / 512GB",
    status: "ใช้งาน",
    category: "Notebook",
    owner: "System Administrator",
    department: "IT Department",
    dueDate: "2027-06-23",
    meta: { serial: "DL7440-TH-001", model: "Latitude 7440", warranty: "ยังมีประกัน", risk: "ต่ำ" }
  }),
  record({
    id: "asset-0002",
    module: "assets",
    code: "IT-2569-00002",
    title: "Monitor Dell P2422H",
    description: "24 inch IPS",
    status: "ว่าง",
    category: "Monitor",
    owner: "คลังอุปกรณ์ IT",
    department: "IT Department",
    dueDate: "2027-02-18",
    meta: { serial: "MON-002", model: "P2422H", warranty: "ยังมีประกัน", risk: "ต่ำ" }
  }),
  record({
    id: "asset-0003",
    module: "assets",
    code: "IT-2569-00003",
    title: "Firewall Fortigate 60F",
    description: "Gateway หลัก HQ",
    status: "ใช้งาน",
    category: "Network",
    owner: "Network Admin",
    department: "IT Department",
    dueDate: "2026-12-31",
    meta: { serial: "FG60F-HQ-01", model: "Fortigate 60F", warranty: "ใกล้หมด", risk: "ปานกลาง" }
  }),
  record({
    id: "checkout-0001",
    module: "checkout",
    code: "CO-2569-00001",
    title: "ยืม Notebook Dell Latitude 7440",
    description: "รับอุปกรณ์ไปใช้งานโครงการ HR onboarding",
    status: "ยืมอยู่",
    category: "Notebook",
    owner: "HR Officer",
    department: "HR",
    dueDate: "2026-07-01",
    meta: { assetTag: "IT-2569-00001", checkoutDate: "2026-06-23", condition: "ดี" }
  }),
  record({
    id: "asset-request-0001",
    module: "asset-requests",
    code: "REQ-ASSET-00001",
    title: "ขอ Notebook สำหรับพนักงานใหม่",
    description: "ต้องใช้เริ่มงานวันที่ 1 กรกฎาคม",
    status: "รอจัดสรร",
    priority: "สูง",
    category: "Notebook",
    owner: "HR Officer",
    department: "HR",
    meta: { assignedAsset: "-", reason: "พนักงานใหม่" }
  }),
  record({
    id: "asset-request-0002",
    module: "asset-requests",
    code: "REQ-ASSET-00002",
    title: "ขอจอมอนิเตอร์ 24 นิ้ว",
    description: "ใช้สำหรับงานบัญชีสองหน้าจอ",
    status: "อนุมัติแล้ว",
    priority: "ปกติ",
    category: "Monitor",
    owner: "Finance Staff",
    department: "Finance",
    meta: { assignedAsset: "IT-2569-00002", reason: "เพิ่มประสิทธิภาพงานเอกสาร" }
  }),
  record({
    id: "asset-audit-0001",
    module: "asset-audit",
    code: "AUDIT-2569-Q2",
    title: "ตรวจนับทรัพย์สินไตรมาส 2",
    description: "ตรวจอุปกรณ์สำนักงาน HQ",
    status: "กำลังตรวจ",
    category: "HQ",
    owner: "IT Support",
    department: "IT Department",
    dueDate: "2026-06-30",
    meta: { found: 42, missing: 0, progress: "72%" }
  }),
  record({
    id: "license-0001",
    module: "licenses",
    code: "LIC-2569-00001",
    title: "Office 2024",
    description: "Microsoft Office perpetual",
    status: "ใกล้หมด",
    category: "Per seat",
    owner: "Microsoft",
    department: "All",
    dueDate: "2026-07-11",
    costMonthly: 1200,
    meta: { seatsUsed: 1, seatsTotal: 10, vendor: "Microsoft", type: "Commercial" }
  }),
  record({
    id: "license-0002",
    module: "licenses",
    code: "LIC-2569-00002",
    title: "Adobe Creative Cloud",
    description: "Design team license",
    status: "ใกล้หมด",
    category: "Subscription",
    owner: "Adobe",
    department: "Marketing",
    dueDate: "2026-07-11",
    costMonthly: 2560,
    meta: { seatsUsed: 3, seatsTotal: 5, vendor: "Adobe", type: "SaaS" }
  }),
  record({
    id: "subscription-0001",
    module: "subscriptions",
    code: "SUB-2569-00001",
    title: "CRM Cloud",
    description: "ระบบ CRM รายเดือน",
    status: "ใช้งาน",
    category: "Cloud",
    owner: "CRM Vendor",
    dueDate: "2027-06-23",
    costMonthly: 3500,
    meta: { cycle: "monthly", autoRenew: true }
  }),
  record({
    id: "subscription-0002",
    module: "subscriptions",
    code: "SUB-2569-00002",
    title: "Hosting",
    description: "Web hosting สำหรับระบบองค์กร",
    status: "ใช้งาน",
    category: "Infrastructure",
    owner: "Hosting Co.",
    dueDate: "2027-07-23",
    costMonthly: 260,
    meta: { cycle: "monthly", autoRenew: true }
  }),
  record({
    id: "budget-0001",
    module: "budget",
    code: "BUD-2569-00001",
    title: "License และ Subscription รายเดือน",
    description: "ค่าใช้จ่ายรวมจาก software และ cloud",
    status: "ติดตาม",
    category: "OPEX",
    owner: "IT Manager",
    costMonthly: 7520,
    meta: { annual: 90240, forecast: "คงที่", vendor: "หลายผู้ขาย" }
  }),
  record({
    id: "vendor-0001",
    module: "vendors",
    code: "VEN-2569-00001",
    title: "Microsoft Thailand",
    description: "License และ Cloud service",
    status: "active",
    category: "Software",
    owner: "Account Manager",
    department: "IT Department",
    dueDate: "2027-12-31",
    meta: { taxId: "0105550000001", phone: "02-000-0000", email: "sales@microsoft.example", website: "https://www.microsoft.com" }
  }),
  record({
    id: "vendor-0002",
    module: "vendors",
    code: "VEN-2569-00002",
    title: "Hosting Co.",
    description: "Hosting และ domain",
    status: "active",
    category: "Infrastructure",
    owner: "Support Team",
    department: "IT Department",
    dueDate: "2027-07-23",
    meta: { taxId: "0105550000002", phone: "02-111-1111", email: "support@hosting.example", website: "https://hosting.example" }
  }),
  record({
    id: "vault-0001",
    module: "vault",
    code: "VAULT-00001",
    title: "MySQL root password",
    description: "Production database credential",
    status: "restricted",
    category: "Database",
    owner: "System Administrator",
    department: "IT Department",
    dueDate: "2026-09-23",
    meta: { username: "root", url: "mysql.internal", accessLevel: "super_admin", rotationDays: 90, passwordHint: "ซ่อนในระบบจริง" }
  }),
  record({
    id: "vault-0002",
    module: "vault",
    code: "VAULT-00002",
    title: "Router admin",
    description: "HQ gateway credential",
    status: "restricted",
    category: "Network",
    owner: "Network Admin",
    department: "IT Department",
    dueDate: "2026-08-15",
    meta: { username: "admin", url: "192.168.1.1", accessLevel: "admin", rotationDays: 60, passwordHint: "ซ่อนในระบบจริง" }
  }),
  record({
    id: "offboarding-0001",
    module: "offboarding",
    code: "OFF-2569-00001",
    title: "Offboarding พนักงานทดลอง",
    description: "เก็บคืนอุปกรณ์และปิดสิทธิ์ระบบ",
    status: "รอดำเนินการ",
    priority: "สูง",
    category: "Employee exit",
    owner: "HR Officer",
    department: "HR",
    dueDate: "2026-06-30",
    meta: { assetsReturn: "รอคืน", accessRevoke: "รอปิดสิทธิ์" }
  }),
  record({
    id: "kb-0001",
    module: "knowledge-base",
    code: "KB-00001",
    title: "วิธีแจ้ง Ticket ให้ครบข้อมูล",
    description: "ใส่อาการ เวลาเกิดปัญหา และ screenshot เพื่อให้ IT วิเคราะห์เร็วขึ้น",
    status: "published",
    category: "Service Desk",
    owner: "IT Support",
    department: "IT Department",
    meta: { tags: "ticket,helpdesk", views: 128 }
  }),
  record({
    id: "kb-0002",
    module: "knowledge-base",
    code: "KB-00002",
    title: "ตั้งค่า VPN สำหรับ Windows",
    description: "ขั้นตอนตั้งค่า VPN และ MFA สำหรับงานนอกสถานที่",
    status: "draft",
    category: "Network",
    owner: "Network Admin",
    department: "IT Department",
    meta: { tags: "vpn,remote", views: 42 }
  }),
  record({
    id: "user-record-admin",
    module: "users",
    code: "USR-00001",
    title: "System Administrator",
    description: "บัญชีผู้ดูแลระบบหลัก",
    status: "active",
    category: "super_admin",
    owner: "admin",
    department: "IT Department",
    meta: { email: "admin@company.local", lastLogin: "2026-06-23 20:37" }
  }),
  record({
    id: "settings-record",
    module: "settings",
    code: "SYS-SETTINGS",
    title: "ITAM Desk",
    description: "ตั้งค่าระบบหลัก, SLA, notification และ upload limit",
    status: "active",
    category: "system",
    owner: "System Administrator",
    department: "IT Department",
    meta: { company: "BUGpairoj Group", itemsPerPage: 20, maxUploadMb: 10, lowSla: 72, mediumSla: 24, highSla: 8, criticalSla: 2 }
  }),
  record({
    id: "profile-record",
    module: "profile",
    code: "ME",
    title: "System Administrator",
    description: "IT Department",
    status: "active",
    category: "super_admin",
    owner: "admin",
    department: "IT Department",
    meta: { email: "admin@company.local", phone: "02-000-0000", lineUserId: "Uid..." }
  })
];

export const seedAuditLogs: AuditLog[] = [
  {
    id: "audit-0001",
    actorId: "admin",
    actorName: "System Administrator",
    module: "auth",
    action: "login",
    recordId: "admin",
    ipAddress: "127.0.0.1",
    createdAt: "2026-06-23T13:37:15.000Z"
  },
  {
    id: "audit-0002",
    actorId: "admin",
    actorName: "System Administrator",
    module: "tickets",
    action: "update_status",
    recordId: "ticket-0001",
    ipAddress: "127.0.0.1",
    createdAt: "2026-06-23T13:45:00.000Z"
  }
];

export const seedSettings: AppSetting[] = [
  {
    key: "system",
    updatedAt: now,
    value: {
      systemName: "ITAM Desk",
      companyName: "BUGpairoj Group",
      companyEmail: "it@example.local",
      companyPhone: "02-000-0000",
      itemsPerPage: 20,
      maxUploadMb: 10,
      lowSla: 72,
      mediumSla: 24,
      highSla: 8,
      criticalSla: 2
    }
  }
];
